services:
  - type: web
    name: scriptflow
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
